#!/bin/bash


# validate data
result=`python scripts/validate-regions.py`
if [[ -n $result ]]; then
  echo $result
  exit 1
fi
result=`python scripts/validate-people.py`
if [[ -n $result ]]; then
  echo $result
  exit 1
fi


# update data
python scripts/people-json.py > people.json
python scripts/regions-json.py > regions.json


# update stats
echo "# Statistics" > statistics.md
echo "" >> statistics.md
echo "On this page are general statistics about breadth and depth of the dataset. These figures are autogenerated whenever the data is updated." >> statistics.md
echo "" >> statistics.md
python scripts/statistics.py >> statistics.md
echo "" >> statistics.md
echo "[Back to homepage.](/catholicdata/)" >> statistics.md


# update repo
echo "Type a commit message, then press [ENTER]:"
git add . && git commit -m "$(read msg && echo $msg)" && git push origin master
